# Generated by Django 5.2.5 on 2025-09-16 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ToDos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="deadLine",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="todo",
            name="finished_at",
            field=models.DateField(null=True),
        ),
    ]
