# Generated by Django 5.2.5 on 2025-09-18 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ToDos", "0003_rename_deadline_todo_deadline"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="deadline",
            field=models.DateField(verbose_name="Data de entrega"),
        ),
        migrations.AlterField(
            model_name="todo",
            name="title",
            field=models.CharField(max_length=100, verbose_name="Titulo"),
        ),
    ]
