# Generated by Django 5.2.1 on 2025-09-24 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ToDos", "0004_alter_todo_deadline_alter_todo_title"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="todo",
            options={"ordering": ["deadline"]},
        ),
    ]
